using Newtonsoft.Json;

namespace EvitaDB.QueryValidator.Serialization.Json;

/// <summary>
/// A <see cref="JsonTextWriter"/> that separates a property name from its value with <c>" : "</c> rather
/// than <c>": "</c>.
///
/// The documentation tests in the evitaDB repository compare this validator's output against fixtures
/// generated by the Java implementation, which serializes through Jackson's <c>DefaultPrettyPrinter</c> -
/// and that printer puts a space on <b>both</b> sides of the separator:
///
/// <code>
/// "primaryKey" : 107891
/// </code>
///
/// Newtonsoft writes <c>"primaryKey": 107891</c> and exposes no setting for the leading space, so the
/// property name is re-emitted here. <c>SetWriteState</c> keeps the writer's own state machine intact
/// (commas and indentation are still its job); only the name and separator are written directly.
///
/// This lives in the validator rather than in the driver on purpose - it exists to match a fixture
/// format, and no other consumer of the driver should inherit it.
/// </summary>
public sealed class JavaStyleJsonTextWriter(TextWriter writer) : JsonTextWriter(writer)
{
    public override void WritePropertyName(string name)
    {
        SetWriteState(JsonToken.PropertyName, name);
        // JsonConvert.ToString applies the same quoting and escaping the base writer would
        WriteRaw(JsonConvert.ToString(name));
        WriteRaw(" :");
    }

    public override void WritePropertyName(string name, bool escape)
    {
        if (escape)
        {
            WritePropertyName(name);
            return;
        }

        // the caller states the name is already escaped, so it is written through unchanged
        SetWriteState(JsonToken.PropertyName, name);
        WriteRaw(QuoteName ? $"\"{name}\"" : name);
        WriteRaw(" :");
    }
}
