using EvitaDB.Client.Exceptions;
using EvitaDB.Client.Models.Schemas;
using EvitaDB.Client.Queries.Filter;

namespace EvitaDB.Client.Models.Data;

/// <summary>
/// Common ancestor for contracts that either directly represent <see cref="IEntity"/> or reference to it
/// - i.e. <see cref="IEntityReference"/>. We don't use sealed interface here because there are multiple implementations
/// of those interfaces but only these two aforementioned extending interfaces could extend from this one.
/// </summary>
public interface IEntityClassifier
{
    /// <summary>
    /// Reference to <see cref="IEntitySchema.Name"/> of the entity. Might be also anything
    /// that identifies type some external resource not maintained by Evita.
    /// </summary>
    public string Type { get; }
    /// <summary>
    /// Unique Integer positive number (max. 2<sup>63</sup>-1) representing the entity. Can be used for fast lookup for
    /// entity (entities). Primary key must be unique within the same entity type.
    /// May be left empty if it should be auto generated by the database.
    /// Entities can be looked up by primary key by using query <see cref="EntityPrimaryKeyInSet"/>
    /// </summary>
    public int? PrimaryKey { get; }

    /// <summary>
    /// The primary key, failing loudly when it has not been assigned yet - the counterpart of Java's
    /// `EntityClassifier.getPrimaryKeyOrThrowException()`, for the many call sites that legitimately require
    /// a stored entity.
    /// </summary>
    /// <exception cref="PrimaryKeyNotAssignedException">when the entity has not been stored yet</exception>
    public int PrimaryKeyOrThrowException => PrimaryKey ?? throw new PrimaryKeyNotAssignedException(Type);
}
