# Builds and releases a new public version of evitaLab a puts it into `Releases` section of GitHub

name: Release

on:
  push:
    branches: ["master"]
    paths:
      - .github/workflows/release.yml
      - EvitaDB.QueryValidator/**.*

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.X'   # setup dotnet 7.0.10 for building

      - name: Build
        run: cd EvitaDB.QueryValidator && dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true --self-contained false && dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true --self-contained false

      - name: Zip 
        uses: vimtor/action-zip@v1
        with:
          dest: 'Validator.zip'
          files: 'EvitaDB.QueryValidator/bin/Release/net7.0/linux-x64/publish/Validator'
          recursive: false

      - name: Zip 
        uses: vimtor/action-zip@v1
        with:
          dest: 'Validator-win.zip'
          files: 'EvitaDB.QueryValidator/bin/Release/net7.0/win-x64/publish/Validator.exe'
          recursive: false

      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ${{ github.workspace }}/Validator.zip
            ${{ github.workspace }}/Validator-win.zip